### ISSUE TITLE
sb-pcl is deprecated - should use sb-mop instead

### ISSUE THREAD

**Issue by quicklisp** [40ants/cl-prevalence#10]
https://github.com/40ants/cl-prevalence/blob/44fe157fa5c5f160b89b929035270e429c10d248/src/serialization/serialization.lisp#L83

The latest SBCL breaks the build on this line.

**Comment by svetlyak40wt** [comment]
Good catch! I definitely need to set up a CI which will check the library on a regular basis!

**Comment by svetlyak40wt** [comment]
> The latest SBCL breaks the build on this line.

I've checked on SBCL 2.0.5 and it works fine, without any warnings:

https://github.com/40ants/cl-prevalence/pull/11

**Comment by svetlyak40wt** [comment]
What is interesting is that cl-prevalence code uses both `sb-pcl` and `sb-mop` simultaneously:
<img width="863" alt="Screenshot 2020-06-22 at 11 58 48" src="https://user-images.githubusercontent.com/24827/85268923-d5db8080-b47f-11ea-9178-8d657008c9e3.png">

**Comment by svetlyak40wt** [comment]
Fixed in https://github.com/40ants/cl-prevalence/pull/13
