### ISSUE TITLE
sexp.lisp: Deserialize struct with `make-instance`

### ISSUE THREAD

**Issue by Ambrevar** [40ants/cl-prevalence#16]
Currently, structures with custom constructors, e.g.

```lisp
(defstruct (uri (:constructor %make-uri))
  scheme
  userinfo
  host
  port
  path
  query
  fragment)
```

fail to deserialize because `deserialize-sexp-internal` tries to call `make-uri` which does not exist.

Instead, I suggest to:

- Check if `(concatenate 'string "MAKE-" (symbol-name class))` exists.
- If it does, call it as we do now.
- If it does not, call `make-instance` instead.

Thoughts?

**Comment by svetlyak40wt** [comment]
Make-instance will not work for defstructs on implementation which implement structs  not as CLOS objects.

Here is an example from SBCL:

```lisp
CL-USER> (defstruct user
           name
           email)
USER
CL-USER> (make-user :name "Bob")
#S(USER :NAME "Bob" :EMAIL NIL)
CL-USER> (make-instance 'user :name "Bob")
; Debugger entered on #<SB-PCL::INITARG-ERROR {1012D96D33}>
[1] CL-USER> 
```

**Comment by svetlyak40wt** [comment]
Hm, it works without arguments:

```
CL-USER> (make-instance 'user)
#S(USER :NAME NIL :EMAIL NIL)
```

Is it legitimate to use `make-instance` to create objects of type `structure-class`?

**Comment by Ambrevar** [comment]
It works, it's just that the initargs are not set.  Replace your example with

```lisp
(let ((object (make-instance 'user)))
  (setf (slot-value object 'name) "Bob"))
```

What I understand from the defstruct HyperSpec:

> If documentation is supplied, it is attached to structure-name as a documentation string of kind structure, and unless :type is used, the documentation is also attached to structure-name as a documentation string of kind type and as a documentation string to the class object for the class named structure-name.

and

> defstruct without a :type option defines a class with the structure name as its name. The metaclass of structure instances is structure-class.

Looks like structures are always classes, aren't they?

**Comment by svetlyak40wt** [comment]
No, here is a [long description](https://stackoverflow.com/questions/34244855/difference-between-struct-and-class-in-common-lisp) of the difference between CLOS classes and structures by Rainer Joswig.

Also, I've checked behaviour on LispWorks, and it does not allow to use make-instance for a structure:

```lisp
CL-USER 1 > (defstruct user
              name
              email)
USER

CL-USER 2 > (make-instance 'user)

Error: No applicable methods for #<STANDARD-GENERIC-FUNCTION MAKE-INSTANCE 40F0093174> with args (#<STRUCTURE-CLASS USER 4020019513>)
  1 (continue) Call #<STANDARD-GENERIC-FUNCTION MAKE-INSTANCE 40F0093174> again
  2 (abort) Return to top loop level 0.

Type :b for backtrace or :c <option number> to proceed.
Type :bug-form "<subject>" for a bug report template or :? for other options.

CL-USER 3 : 1 > 
```

**Comment by Ambrevar** [comment]
What about adding feature macros then, e.g. #+SBCL.

Is it possible to query a struct constructor?

Any other suggestion?

Ideally, deserialize-sexp-internal would be a method which would
specialize on the different types, just like serialize-sexp-internal.

Then we could fix this kind of errors on a per-struct basis.

**Comment by svetlyak40wt** [comment]
@Ambrevar feel free to experiment and make a pull.

I'd prefer a solution which can work better on some implementation and signal about the problem on others.

**Comment by Ambrevar** [comment]
OK, I'll send a patch.

I've tried with different compilers:

- SBCL: OK
- CCL: OK
- ECL: OK
- CLisp: OK
- ABCL: Nope, (make-instance 'user) returns an error.

**Comment by svetlyak40wt** [comment]
Thank you!
