### ISSUE TITLE
The tests assume order of execution of the tests

### ISSUE THREAD

**Issue by Yehouda** [40ants/cl-prevalence#8]
The tests assume order of execution, because some of them  set up things like *test-system* and other tests use it. But Fiveam does not execute the tests in a specific order, unless there are dependencies that define the order. 

Fiveam does loop for the hash table in the suite, so the order execution depends on how hash-table are implemented, and at least in LispWorks that means the order is undefined and can change whenever the hash table is rehashed.

**Comment by svetlyak40wt** [comment]
Please, make a pull request.

ср, 19 февр. 2020 г., 19:32 Yehouda Harpaz <notifications@github.com>:

**Comment by Yehouda** [comment]
I don't work on it, I just loaded it using Quicklisp and try the test.

**Comment by svetlyak40wt** [comment]
Ok.

чт, 20 февр. 2020 г., 12:58 Yehouda Harpaz <notifications@github.com>:

**Comment by svetlyak40wt** [comment]
May be will be fixed later.
